### PR TITLE
CC-19289 Added new Unzer doc

### PR DESCRIPTION
**Pull request by kkicheglovspryker**
## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

### CODE REVIEW

**Review by jeremyfourna — CHANGES_REQUESTED** [review]
Please add screenshots of the checkout process and all the steps that the customer will see in the checkout to show that your guide works. Add the screenshots or screen recordings to this PR, and the TW team will upload them.

**Comment by kkicheglovspryker** [comment]
Screenshot_20220726_114634
Screenshot_20220726_114612
Screenshot_20220726_114549
Screenshot_20220726_112007
Screenshot_20220726_111953
Screenshot_20220726_111916
Screenshot_20220726_111542
Screenshot_20220726_111507

**Review by jeremyfourna — APPROVED** [review]

**Comment by jeremyfourna** [comment]
@VadymSachenko can you add the screenshots at the end of the doc with a separation between the order detail page in the OMS and the PayPal screenshots in the Cart & Checkout process?

**Comment by VadymSachenko** [comment]
@jeremyfourna I'll do my best

**Comment by VadymSachenko** [comment]
@jeremyfourna to which document do you want me to add these screenshots?

**Comment by jeremyfourna** [comment]
@VadymSachenko `docs/pbc/all/payment-service-providers/unzer/extend-and-customize/new-payment-methods-on-project.md`

**Review by VadymSachenko — COMMENTED** [review]
Reviewed the document, and added screenshots.

**Review by jeremyfourna — APPROVED** [review]
OK for me

**Review by VadymSachenko — APPROVED** [review]

**Review by VadymSachenko — APPROVED** [review]

**Review by VadymSachenko — APPROVED** [review]

**Pull request merged**
